### ISSUE TITLE
Which exact LEDs were used?

### ISSUE THREAD

**Issue by Chaitran77** [atomic14/usb-tester#1]
Hi, 
I was wondering which exact LEDs or LED series you used to build this. Just a part number or anything would be super useful!

Thanks.

**Comment by cgreening** [comment]
I used a bunch of unbranded random 0603 from a book of LEDs I got from AliExpress. Any LEDs will work.

**Comment by Chaitran77** [comment]
Thank you. I was asking for the exact ones because it initially looked like the solder joints were to the side faces of each LED (I couldn't find SMD LEDs like that) but I later noticed they're actually to a small flange/piece of PCB that sticks out from either side of the LED.

I'll close this issue now but if anyone has more information about this please ff to reply :)
